package com.example.termiti

/**
 * Prezentační data karty – vše, co je specifické pro Android klienta.
 * Herní data (cost, effects, rarity…) jsou v cards.js / cards.json.
 *
 * Při přidání nové karty do cards.js stačí volitelně přidat záznam sem
 * pro art, zvuk a popis. Karta bez záznamu funguje, ale zobrazí se
 * bez ilustrace a s prázdným popisem.
 */
data class CardPres(
    val description:   String    = "",
    val artResId:      Int?      = null,
    val type:          String    = "",
    val artBiasX:      Float     = 0f,
    val artBiasY:      Float     = 0f,
    val artScale:      Float     = 1f,
    val isBasic:       Boolean   = false,
    val sound:         CardSound? = null,
    val soundResId:    Int?      = null,
    /**
     * LEGACY — no longer read. All localized card text (names + descriptions for every
     * language, including English) now lives in assets/lang/<code>.json under "cards".
     * Kept only so existing call sites compile; safe to drop in a future cleanup.
     */
    val descriptionEn: String    = "",
    /**
     * Skloňovaný název karty ve 4. pádu (akuzativ) pro použití v log zprávách,
     * např. "lízl Bombu". Pokud null, použije se [Card.name] bez skloňování.
     */
    val nameAccusative: String?  = null
)

object CardPresentation {
    val presentations: Map<String, CardPres> = mapOf(

        // ── Útok (platí ATTACK) ───────────────────────────────────────────────
        "001" to CardPres("Zaútočí na nepřítele za 6.\n[Combo]",
            R.drawable.art_zakladni_utok, "Útok", isBasic = true),
        "008" to CardPres("Zaútočí na hrad za 3. [Combo]",
            R.drawable.art_sipy, "Útok",
            soundResId = R.raw.arrow_hit),
        "003" to CardPres("Udeř hrad −8.",
            R.drawable.art_ohniva_koule, "Magie", artBiasY = -0.60f,
            soundResId = R.raw.fireball),
        "007" to CardPres("Zaútočí na nepřítele za 11.",
            R.drawable.art_silny_uder, "Útok",
            artScale = 0.80f, artBiasY = -1.00f, isBasic = true),
        "006" to CardPres("Pokud máš více útoku než soupeř, udeř hrad za 10.",
            R.drawable.art_prevaha_sily, "Útok",
            artScale = 0.80f, artBiasY = -0.10f),
        "017" to CardPres("Zaútočí za 8, ukradni 2 útoku soupeři.",
            R.drawable.art_valecny_sekyrnik, "Útok",
            artScale = 0.80f, artBiasY = -1.00f),

        // ── Stavba (platí STONES) ─────────────────────────────────────────────
        "002" to CardPres("Hradby +9, vrátí 1 kámen.",
            R.drawable.art_kamenna_zed, "Stavba",
            artBiasX = -0.50f, artBiasY = -1.00f, artScale = 0.80f, isBasic = true),
        "010" to CardPres("Hradby +6, vrátí 1 kámen.",
            R.drawable.art_palisada, "Stavba",
            artScale = 0.80f, artBiasY = -1.00f, isBasic = true),
        "005" to CardPres("Opraví hrad o 5.",
            R.drawable.art_posila_hradu, "Stavba",
            artScale = 0.80f, artBiasY = -0.30f, isBasic = true),
        "009" to CardPres("Opraví hrad o 8, vrátí 1 kámen.",
            R.drawable.art_pevne_zaklady, "Stavba",
            artScale = 0.80f, artBiasY = 0.50f, isBasic = true),
        "018" to CardPres("Postaví hradby +15.",
            R.drawable.art_mohutna_vez, "Stavba",
            artScale = 0.90f, artBiasY = -1.00f),

        // ── Zdroje okamžité (platí MAGIC) ────────────────────────────────────
        "004" to CardPres("Magie +2.\n[Combo]",
            R.drawable.art_magie, "Magie", artBiasY = -1.00f, isBasic = true),
        "011" to CardPres("Kameny +3.\n[Combo]",
            R.drawable.art_zasoby_kamene, "Magie",
            artScale = 0.80f, artBiasY = -0.55f, isBasic = true),
        "012" to CardPres("Útok +3.\n[Combo]",
            R.drawable.art_mobilizace, "Magie",
            artScale = 0.80f, artBiasY = -0.30f, isBasic = true),

        // ── Doly (platí MAGIC) ────────────────────────────────────────────────
        "013" to CardPres("Důl magie +1.",
            R.drawable.art_magicky_pramen, "Důl",
            artScale = 0.80f, artBiasY = -0.40f, isBasic = true),
        "014" to CardPres("Důl kamene +1.",
            R.drawable.art_kamenolom, "Důl",
            artScale = 0.75f, artBiasY = -0.30f, isBasic = true),
        "015" to CardPres("Důl útoku +1.",
            R.drawable.art_vycvikovy_tabor, "Důl",
            artScale = 0.85f, artBiasY = -0.20f, isBasic = true),
        "016" to CardPres("Doly magie +2.",
            R.drawable.art_velky_pramen, "Důl",
            artScale = 0.75f, artBiasY = -0.55f),

        // ── Útok – rozšíření ──────────────────────────────────────────────────
        "019" to CardPres("Poškodí hradby o 5.\n[Combo]",
            R.drawable.art_zapalne_sipy, "Útok",
            artScale = 0.80f, artBiasY = -1.00f, soundResId = R.raw.arrow_hit),
        "020" to CardPres("Poškodí jen hradby o 12.\n[Combo]",
            R.drawable.art_beranidlo, "Útok",
            artScale = 0.85f, artBiasY = 0.05f),
        "021" to CardPres("Zaútočí na nepřítele za 15.",
            R.drawable.art_delostrelectvo, "Útok",
            artScale = 0.80f, artBiasY = 0.05f, soundResId = R.raw.delostrelectvo),
        "022" to CardPres("Poškodí hrad −8.",
            R.drawable.art_primy_zasah, "Útok",
            artScale = 0.80f, artBiasY = -1.00f),
        "023" to CardPres("Zaútočí na hrad za 7 a na soupeře za 7.",
            R.drawable.art_dvojity_utok, "Útok",
            artScale = 0.80f, artBiasY = -1.00f),
        "024" to CardPres("Pokud máš <5 hradeb, udeř hrad za 12.",
            R.drawable.art_berserk, "Útok",
            artScale = 0.75f, artBiasY = -0.50f),
        "025" to CardPres("Pokud máš <10 hradeb, udeř hrad za 10.",
            R.drawable.art_protiutok, "Útok",
            artScale = 0.80f, artBiasY = -0.50f),
        "026" to CardPres("Poškodí hrad o 5. Pokud >5 útoku, +5.",
            R.drawable.art_ostrelovac, "Útok",
            artScale = 0.85f, artBiasY = 0.10f),
        "027" to CardPres("Zaútočí za 4. **Toto kolo:** za každou zahranou **ÚTOK** +2 útoku. [Combo]",
            R.drawable.art_valecne_bubny, "Útok",
            artScale = 0.80f, artBiasY = -0.60f, soundResId = R.raw.drums_of_war),

        // ── Stavba – rozšíření ────────────────────────────────────────────────
        "028" to CardPres("Hrad +3.\n[Combo]",
            R.drawable.art_zaplata, "Stavba",
            artBiasX = 0.50f, artBiasY = -1.00f, artScale = 0.85f),
        "029" to CardPres("Hradby +6, hrad +2.",
            R.drawable.art_opevneni, "Stavba",
            artScale = 0.80f, artBiasY = 0.55f),
        "030" to CardPres("Postaví hradby +13.",
            R.drawable.art_kamenny_val, "Stavba",
            artScale = 0.80f, artBiasY = -1.00f),
        "031" to CardPres("Opraví hrad o 7.",
            R.drawable.art_renovace, "Stavba",
            artScale = 0.85f, artBiasY = -1.00f, isBasic = true),
        "032" to CardPres("Opraví hrad o 13.",
            R.drawable.art_citadela, "Stavba",
            artScale = 0.80f, artBiasY = -0.80f),
        "033" to CardPres("Pokud máš <8 hradeb, postav +11.",
            R.drawable.art_zemni_val, "Stavba",
            artScale = 0.80f, artBiasY = -1.00f),
        "034" to CardPres("Pokud máš >15 hradeb, oprav hrad o 9.",
            R.drawable.art_opravar, "Stavba",
            artScale = 0.80f, artBiasY = 0.25f),
        "035" to CardPres("Hradby +5 a hrad +4.",
            R.drawable.art_zakladni_kamen, "Stavba",
            artScale = 0.80f, artBiasY = 0.25f),
        "036" to CardPres("Hradby +7. Pokud hrad <35, hradby +5.",
            R.drawable.art_hradni_prikop, "Stavba",
            artScale = 0.80f, artBiasY = -0.95f),

        // ── Zdroje – rozšíření ────────────────────────────────────────────────
        "037" to CardPres("Magie +4.\n[Combo]",
            R.drawable.art_rychla_magie, "Magie",
            artScale = 0.75f, artBiasY = -0.35f),
        "038" to CardPres("Útok +6.\n[Combo]",
            R.drawable.art_vojensky_rozkaz, "Magie",
            artScale = 0.80f, isBasic = true),
        "039" to CardPres("Kámen +6.\n[Combo]",
            R.drawable.art_stavebni_boom, "Magie",
            artScale = 0.80f, artBiasY = 0.25f, isBasic = true),
        "040" to CardPres("Pokud máš >4 magie, získej +8 útoku.",
            R.drawable.art_alchymie, "Magie"),
        "041" to CardPres("Magie +2, útok +2, kámen +2.\n[Combo]",
            R.drawable.art_magicke_trio, "Magie",
            artScale = 0.80f, artBiasY = -1.00f),

        // ── Doly – rozšíření ──────────────────────────────────────────────────
        "042" to CardPres("Doly kamene +2.",
            R.drawable.art_velky_kamenolom, "Důl",
            artScale = 0.80f, artBiasY = 0.25f),
        "043" to CardPres("Doly útoku +2.",
            R.drawable.art_vycvikove_centrum, "Důl",
            artScale = 0.85f),
        "044" to CardPres("Důl magie, útoku i kamene +1.",
            R.drawable.art_trifekta_dolu, "Důl",
            artScale = 0.80f, artBiasY = -0.35f),
        "045" to CardPres("Doly magie +3.",
            R.drawable.art_ocarovane_doly, "Důl",
            artScale = 0.80f),

        // ── Útok – Arcomage/Mravenci inspirace ────────────────────────────────
        "046" to CardPres("Zaútočí za 2, ukradni 1 magii, chaos +1.",
            R.drawable.art_goblin, "Útok", artScale = 0.80f),
        "047" to CardPres("Zaútočí na nepřítele za 9.",
            R.drawable.art_ogr, "Útok",
            artScale = 0.80f, isBasic = true, soundResId = R.raw.ogr),
        "048" to CardPres("Zaútočí za 6, získej +3 magie.\n[Combo]",
            R.drawable.art_upir, "Útok",
            artScale = 0.80f, artBiasY = -1.00f),
        "049" to CardPres("Zaútočí za 3, soupeř ztratí 3 magie, chaos +2.",
            R.drawable.art_jed, "Útok",
            artScale = 0.80f, artBiasY = -0.50f, soundResId = R.raw.jed),
        "050" to CardPres("Zaútočí za 8, soupeř ztratí 4 kameny.",
            R.drawable.art_podkopani_hradeb, "Útok",
            artScale = 0.80f, artBiasY = 0.35f),
        "051" to CardPres("Zaútočí za 14, hrad −8, chaos +3.",
            R.drawable.art_drak, "Útok",
            artScale = 0.80f, artBiasY = -1.00f, soundResId = R.raw.dragon_breath),
        "052" to CardPres("Udeř hrad −16. Chaos +4.",
            R.drawable.art_demon, "Útok",
            artScale = 0.80f, artBiasY = -0.50f, soundResId = R.raw.demon_laugh),
        "053" to CardPres("Poškodí jen hradby o 10, získej +2 útoku.",
            R.drawable.art_plamenomet, "Útok",
            artBiasX = -1.00f, artBiasY = -0.05f, artScale = 0.80f),
        "054" to CardPres("Zaútočí na nepřítele za 13, +2 útoku.",
            R.drawable.art_valecny_pochod, "Útok",
            artScale = 0.80f, artBiasY = -0.30f),
        "055" to CardPres("Zaútočí za 3, +1 útok. Pokud <5 hradeb: hrad −8.",
            R.drawable.art_posledni_vzdor, "Útok",
            artScale = 0.80f, artBiasY = -1.00f),
        "056" to CardPres("Ukradni 3 útoku, zaútočí za 4.",
            R.drawable.art_najezdnik, "Útok",
            artScale = 0.80f, artBiasY = -0.65f, isBasic = true),

        // ── Stavba – Arcomage/Mravenci inspirace ──────────────────────────────
        "057" to CardPres("Hradby +3, hrad +5.",
            R.drawable.art_basta, "Stavba",
            artScale = 0.80f, artBiasY = -1.00f),
        "058" to CardPres("Hradby +4.\n[Combo]",
            R.drawable.art_obranny_val, "Stavba",
            artScale = 0.80f),
        "059" to CardPres("Hradby +4, hrad +6, soupeř ztratí 1 útok.",
            R.drawable.art_pevnostni_hrad, "Stavba",
            artScale = 0.80f, artBiasY = -0.50f, isBasic = true),
        "060" to CardPres("Hrad +18.",
            R.drawable.art_chram, "Stavba",
            artScale = 0.80f, artBiasY = -0.25f),
        "061" to CardPres("Hrad +4. Zablokuj soupeřův útočný důl na 1 kolo.",
            R.drawable.art_tunely, "Stavba",
            artScale = 0.80f),
        "062" to CardPres("Hradby +6, hrad +5, +2 kameny.",
            R.drawable.art_obranna_aliance, "Stavba",
            artScale = 0.80f, artBiasY = -0.05f),
        "063" to CardPres("Hradby +11, důl kamene +1.",
            R.drawable.art_vez_strazni, "Důl",
            artScale = 0.80f, artBiasY = -1.00f),
        "064" to CardPres("Pokud hrad <40, oprav hrad o 10.",
            R.drawable.art_zasobnik, "Stavba",
            artScale = 0.80f, artBiasY = -0.50f),

        // ── Sabotáž a krádež (platí MAGIC) ────────────────────────────────────
        "065" to CardPres("Ukradni 4 útoku od soupeře.",
            R.drawable.art_lupic, "Magie",
            artScale = 0.80f, artBiasY = 0.05f, isBasic = true),
        "066" to CardPres("Ukradni 4 kameny od soupeře.",
            R.drawable.art_kamenna_dan, "Magie",
            artScale = 0.80f),
        "067" to CardPres("Soupeř ztratí 5 kamenů.",
            R.drawable.art_saboter, "Magie",
            artBiasX = -1.00f, artBiasY = 0.40f, artScale = 0.80f),
        "068" to CardPres("Soupeř ztratí 5 útoku.",
            R.drawable.art_demoralizace, "Magie",
            artScale = 0.80f, artBiasY = 0.30f),
        "069" to CardPres("Ukradni 3 magie a 3 útoku, +2 chaosu.",
            R.drawable.art_dvojity_agent, "Magie",
            artScale = 0.80f, artBiasY = -0.60f),
        "070" to CardPres("Soupeř ztratí 5 kamenů a 5 útoku.",
            R.drawable.art_krize_zasobovani, "Magie",
            artScale = 0.80f, artBiasY = -0.05f),
        "071" to CardPres("Ukradni 1 od každého zdroje. +2 Chaos.",
            R.drawable.art_spion, "Magie",
            artScale = 0.80f, artBiasY = -1.00f),

        // ── Zdroje + doly – Arcomage/Mravenci inspirace ───────────────────────
        "072" to CardPres("Útok +2, důl útoku +1.",
            R.drawable.art_zbrojnice, "Doly",
            artScale = 0.80f, artBiasY = 0.60f),
        "073" to CardPres("Magie +2, důl magie +1.",
            R.drawable.art_skola_magie, "Důl",
            artScale = 0.80f, artBiasY = 0.30f),
        "074" to CardPres("Magie +3, útok +3, kámen +3.\n[Combo]",
            R.drawable.art_trziste, "Magie",
            artScale = 0.80f, artBiasY = 0.30f),
        "075" to CardPres("Doly magie +2, důl kamene +1.",
            R.drawable.art_rozmach_tezby, "Důl",
            artScale = 0.80f, artBiasY = -1.00f),
        "076" to CardPres("Doly útoku +2, důl kamene +1.",
            R.drawable.art_vojenska_zakladna, "Důl",
            artScale = 0.80f, artBiasY = -1.00f),
        "077" to CardPres("Pokud máš >8 magie, získej +10 útoku.",
            R.drawable.art_premena_magie, "Magie",
            artScale = 0.80f, artBiasY = -1.00f),
        "078" to CardPres("Hrad −10, ukradni 4 magie a 4 útoku, +3 chaosu.",
            R.drawable.art_draci_upir, "Útok",
            artScale = 0.80f, artBiasY = -1.00f, soundResId = R.raw.dragon_breath),
        "079" to CardPres("Zaútočí za 12, soupeř ztratí 3 magie, +2 chaosu.",
            R.drawable.art_oblehani, "Útok",
            artScale = 0.75f, artBiasY = -0.45f),
        "080" to CardPres("Každý důl +2.",
            R.drawable.art_velkovyroba, "Důl",
            artScale = 0.80f),

        // ── Stavba – nové posily (STONES buff) ───────────────────────────────
        "131" to CardPres("Zaútočí za 6. Zničí 1 kamenný důl soupeře (min. 1).",
            R.drawable.art_invaze, "Útok",
            artScale = 0.80f, artBiasY = 0.00f,
            descriptionEn = "Attack for 8. Destroy 1 of the opponent's Stone mines (min. 1).",
            nameAccusative = "Invazi"),
        "130" to CardPres("Útok +2, kameny −2.\n[Combo]",
            R.drawable.art_rabovani, "Útok",
            artScale = 0.80f, artBiasY = 0.10f),
        "129" to CardPres("Zeď +2 a hrad +2. Zlevní náhodnou **STAVBA** kartu v ruce o 2.",
            R.drawable.art_priprava, "Stavba",
            artScale = 0.80f, artBiasY = -0.20f),
        "081" to CardPres("Hradby +6.\n[Combo]",
            R.drawable.art_rychla_hradba, "Stavba",
            artScale = 0.80f, artBiasY = -0.65f),
        "082" to CardPres("Hradby +18.",
            R.drawable.art_masivni_zed, "Stavba",
            artScale = 0.80f, artBiasY = -0.45f),
        "083" to CardPres("Pokud máš <10 hradeb, postav +14.",
            R.drawable.art_nouzove_opevneni, "Stavba",
            artScale = 0.80f, artBiasY = -0.60f),
        "084" to CardPres("Hradby +5 a hrad +7.",
            R.drawable.art_velka_oprava, "Stavba",
            artScale = 0.80f, artBiasY = -0.20f),
        "085" to CardPres("Hrad +15.",
            R.drawable.art_kralovska_obnova, "Stavba",
            artScale = 0.80f, artBiasY = 0.50f),
        "086" to CardPres("Hradby +8 a hrad +6.",
            R.drawable.art_zednicka_rota, "Stavba",
            artScale = 0.80f),
        "087" to CardPres("Hradby +10 a hrad +8.",
            R.drawable.art_pevnost, "Stavba",
            artScale = 0.80f, artBiasY = -1.00f),
        "088" to CardPres("Hradby +10. Pokud máš >30 hradu, +6 navíc.",
            R.drawable.art_zesilene_hradby, "Stavba",
            artScale = 0.80f, artBiasY = -1.00f),
        "089" to CardPres("Hradby +5, důl kamene +1.",
            R.drawable.art_architekt, "Důl",
            artScale = 0.80f, artBiasY = -0.60f),
        "090" to CardPres("Doly kamene +2.",
            R.drawable.art_rozsireni_tezby, "Důl",
            artScale = 0.80f, artBiasY = -0.25f),
        "091" to CardPres("Hradby +9. Soupeř ztratí 2 útoku.",
            R.drawable.art_barikady, "Stavba",
            artScale = 0.80f, artBiasY = -0.95f),
        "092" to CardPres("Hradby +5. Vyber si 1 kartu z horních 4 karet svého balíčku.",
            R.drawable.art_strategicka_vystavba, "Stavba",
            artScale = 0.80f, artBiasY = -0.55f),
        "093" to CardPres("Hrad +5. **Toto kolo:** za každou zahranou **STAVBU** +3 hrad. [Combo]",
            R.drawable.art_cihla_na_cihlu, "Stavba",
            artScale = 0.90f, artBiasY = -1.00f),
        "094" to CardPres("Hradby +6, získej +2 kameny. [Combo]",
            R.drawable.art_sklad_materialu, "Stavba",
            artScale = 0.80f),
        "095" to CardPres("Kámen +5.",
            R.drawable.art_obchod_s_kamenem, "Stavba",
            artScale = 0.80f),
        "096" to CardPres("Hradby +18, Hrad +8.",
            R.drawable.art_nedobytna_pevnost, "Stavba",
            artScale = 0.80f),
        "097" to CardPres("Hrad +25.",
            R.drawable.art_obnova_kralovstvi, "Stavba",
            artScale = 0.80f),
        "098" to CardPres("Vlastní hradby −4, zaútočí na nepřítele za 11.",
            R.drawable.art_hod_cihlou, "Útok",
            artScale = 0.80f, artBiasY = 0.15f),
        "099" to CardPres("Ukradni 10 HP hradu soupeři.",
            R.drawable.art_temny_prenos, "Magie",
            artScale = 0.80f, artBiasY = -1.00f),
        "100" to CardPres("Zaútočí za 5, ukradni 6 životů hradu.",
            R.drawable.art_krvavy_uder, "Útok",
            artBiasX = -1.00f, artScale = 0.80f),

        // ── X-kost karty ──────────────────────────────────────────────────────
        "101" to CardPres("Spotřebuje veškerý útok. Přímý zásah hradu za X/2.",
            R.drawable.art_nahla_smrt, "Útok",
            artBiasX = 0.25f, artBiasY = -0.30f, artScale = 0.80f),
        "102" to CardPres("Spotřebuje veškerý kámen. Opraví hrad o X/2.",
            R.drawable.art_kamenny_prival, "Stavba",
            artScale = 0.80f, artBiasY = -1.00f),
        "103" to CardPres("Spotřebuje veškerou magii. Přidá X/2 útoku a X/2 kamene.",
            R.drawable.art_magicke_rozdeleni, "Magie",
            artScale = 0.80f, artBiasY = -0.40f),
        "108" to CardPres("**Rozhodnutí:** Nahlédni do soupeřova balíku a zahoď 1 kartu.",
            R.drawable.art_likvidace, "Chaos",
            artScale = 0.80f, artBiasY = -1.00f),
        "109" to CardPres("**Rozhodnutí:** Vyber si 1 útočnou kartu ze hry. Zlevni ji o 2. [Combo]",
            R.drawable.art_rekrut, "Útok",
            artScale = 0.80f, artBiasY = -1.00f),
        "112" to CardPres("**Rozhodnutí:** Vyber si 1 stavební kartu ze hry. Zlevni ji o 2. [Combo]",
            R.drawable.art_stavitel, "Stavba",
            artScale = 0.80f, artBiasY = -1.00f),
        "110" to CardPres("**Rozhodnutí:** Vyber si 1 kartu z odhazovacího balíčku.",
            R.drawable.art_vzpominka, "Magie",
            artScale = 0.80f, artBiasY = -1.00f),
        "111" to CardPres("**Rozhodnutí:** Prohledej vlastní balíček a vyber si 1 kopii karty.",
            R.drawable.art_intuice, "Magie",
            artScale = 0.80f, artBiasY = -1.00f),
        "104" to CardPres("Zaútočí za 5, důl útoku +1. [Combo]",
            R.drawable.art_valecny_trenink, "Důl",
            artScale = 0.80f, artBiasY = -1.00f),
        "107" to CardPres("Zaútočí za 3, soupeř ztratí 3 útoku a 3 kamenů. Chaos +2.",
            R.drawable.art_prokleti, "Magie",
            artScale = 0.80f, artBiasY = -1.00f),

        // ── Chaos – generátory chaosu ────────────────────────────────────────
        "C01" to CardPres("Chaos +2.\n[Combo]",
            R.drawable.art_chaoticka_jiskra, "Chaos",
            artScale = 0.80f, artBiasY = -1.00f),
        "C02" to CardPres("Chaos +5. Soupeř ztratí 2 magie.",
            R.drawable.art_entropie, "Magie",
            artScale = 0.80f),
        "C03" to CardPres("Důl chaosu +1.",
            R.drawable.art_chaoticky_dul, "Důl",
            artScale = 0.80f),
        "C04" to CardPres("Ukradni 3 chaos od soupeře. [Combo]",
            R.drawable.art_kradez_chaosu, "Magie",
            artScale = 0.80f, artBiasY = -0.55f),

        // ── Chaos – karty platící chaosem ────────────────────────────────────
        "C05" to CardPres("Hrad −14.",
            R.drawable.art_chaoticky_vybuch, "Chaos",
            artScale = 0.80f, artBiasY = 0.30f),
        "C06" to CardPres("Zaútočí na nepřítele za 20.",
            R.drawable.art_boure_chaosu, "Chaos",
            artScale = 0.75f, artBiasY = -0.60f),
        "C07" to CardPres("Hradby +16.",
            R.drawable.art_chaoticky_stit, "Stavba",
            artScale = 0.80f, artBiasY = -0.20f),
        "C08" to CardPres("Hrad +15.",
            R.drawable.art_zazrak_chaosu, "Stavba",
            artScale = 0.80f, artBiasY = -0.20f),
        "C09" to CardPres("Soupeř ztratí 6 od každého zdroje.",
            R.drawable.art_chaoticka_krize, "Chaos",
            artScale = 0.80f),
        "C10" to CardPres("Zaútočí za 15, hrad −12 přímo.",
            R.drawable.art_chaoticky_drak, "Chaos",
            artScale = 0.80f, artBiasY = -1.00f, soundResId = R.raw.dragon_breath),
        "C11" to CardPres("Hrad +8 a hradby +8.",
            R.drawable.art_chaos_a_rad, "Stavba",
            artScale = 0.80f, artBiasY = -0.35f),
        "C12" to CardPres("Ukradni 5 od každého zdroje.",
            R.drawable.art_anarchie, "Chaos",
            artScale = 0.80f, artBiasY = -0.90f),

        // ── Chaos – ničení dolů ───────────────────────────────────────────────
        "C13" to CardPres("Znič 1 důl magie (min. 1). Zablokuj produkci na 2 kola.",
            R.drawable.art_sabotaz, "Chaos",
            artScale = 0.80f, artBiasY = -0.20f),
        "C14" to CardPres("Znič 1 důl kamene (min. 1). Zablokuj produkci na 2 kola.",
            R.drawable.art_niceni_kamenolomu, "Chaos",
            artScale = 0.80f, artBiasY = -0.85f),
        "C15" to CardPres("Znič 1 útočný výcvik (min. 1). Zablokuj produkci na 2 kola.",
            R.drawable.art_zakernost, "Chaos",
            artScale = 0.80f, artBiasY = 0.35f),
        "C16" to CardPres("Znič důl magie a kamene (min. 1). Zablokuj produkci na 3 kola.",
            R.drawable.art_velka_sabotaz, "Chaos",
            artScale = 0.80f, artBiasY = -1.00f),

        // ── Chaos – krádež a ničení karet ─────────────────────────────────────
        "C17" to CardPres("Ukradni 1 náhodnou kartu ze soupeřovy ruky.",
            R.drawable.art_telekineze, "Chaos",
            artScale = 0.80f, artBiasY = -1.00f),
        "C18" to CardPres("Ukradni 2 náhodné karty ze soupeřovy ruky.",
            R.drawable.art_kradez_osudu, "Chaos",
            artScale = 0.80f, artBiasY = -0.75f),
        "C19" to CardPres("Znič 2 náhodné karty ze soupeřovy ruky.",
            R.drawable.art_spalena_knihovna, "Chaos",
            artScale = 0.80f, artBiasY = 0.10f),
        "C20" to CardPres("Znič 3 náhodné karty ze soupeřovy ruky.",
            R.drawable.art_prazdna_mysl, "Chaos",
            artScale = 0.80f, artBiasY = -0.45f),

        // ── Chaos – přidání karet do balíčku ──────────────────────────────────
        "C21" to CardPres("Přidej 3 kopie 'Šípy' do svého balíčku.",
            R.drawable.art_replikace, "Chaos",
            artScale = 0.80f, artBiasY = -0.35f),
        "C22" to CardPres("Přidej 2x 'Chaos výbuch' do svého balíčku.",
            R.drawable.art_chaos_manufaktura, "Chaos",
            artScale = 0.80f),
        "C23" to CardPres("Přidej 2 kopie 'Rychlý útok' do svého balíčku.",
            R.drawable.art_klonovani, "Chaos",
            artScale = 0.75f, artBiasY = -0.20f),

        // ── Chaos – nové generátory ───────────────────────────────────────────
        "C24" to CardPres("Chaos +5.\n[Combo]",
            R.drawable.art_temny_ritual, "Magie",
            artScale = 0.80f, artBiasY = 0.30f),
        "C25" to CardPres("Chaos +2, magie +2.\n[Combo]",
            R.drawable.art_nestabilni_vir, "Magie",
            artScale = 0.80f, artBiasY = -0.75f),
        "C26" to CardPres("Chaos +3.\n[Combo]",
            R.drawable.art_krvava_obet, "Magie",
            artScale = 0.80f),
        "C27" to CardPres("Pokud máš >5 magie, získej +7 chaosu.",
            R.drawable.art_odraz_magie, "Magie",
            artScale = 0.80f, artBiasY = -1.00f),
        "C28" to CardPres("Ukradni 2 útoku, chaos +2.\n[Combo]",
            R.drawable.art_chaoticka_trofej, "Chaos",
            artScale = 0.80f, artBiasY = -0.95f),
        "C29" to CardPres("Chaos +3, důl chaosu +1.",
            R.drawable.art_bourliva_mysl, "Důl",
            artScale = 0.80f, artBiasY = -0.75f),
        "C30" to CardPres("Doly chaosu +2.",
            R.drawable.art_chram_chaosu, "Důl",
            artScale = 0.80f, artBiasY = -0.10f),
        "C31" to CardPres("+4 chaosu, soupeř ztratí 2 od každého zdroje.",
            R.drawable.art_chaoticky_vymenik, "Chaos",
            artScale = 0.80f, artBiasY = 0.55f),
        "C32" to CardPres("Soupeř −10 hrad, vlastní hrad −10.",
            R.drawable.art_vzajemna_zkaza, "Chaos",
            artScale = 0.80f, artBiasY = -0.40f),
        "C33" to CardPres("Prohoď s oponentem celé ruce karet.",
            R.drawable.art_kradez_identity, "Chaos",
            artScale = 0.80f, artBiasY = -0.75f),
        "C34" to CardPres("Na začátku každého tahu se promění v náhodnou kartu ze hry.",
            R.drawable.art_shapeshifter, "Chaos",
            artScale = 0.90f, artBiasY = -0.75f),
        "C35" to CardPres("Zničí jeden vlastní **DŮL MAGIE** a přemění ho na **DŮL CHAOSU**. Nelze snížit pod 1.",
            R.drawable.art_chaoticka_premena, "Důl",
            artScale = 0.80f, artBiasY = -0.75f),
        "C36" to CardPres("Zamíchá **3 BOMBY** do soupeřova balíčku. Po líznutí bomby **HRAD -5**.",
            R.drawable.art_skryta_bomba, "Chaos",
            artScale = 0.80f, artBiasY = -0.10f,
            descriptionEn = "Shuffles **3 BOMBS** into the opponent's deck. Drawing a bomb deals **CASTLE -5**."),
        "C37" to CardPres("**VÝBUCH! Hrad -5. (past – spustí se při líznutí)**",
            R.drawable.art_skryta_bomba, "Chaos",
            artScale = 0.80f, artBiasY = -0.10f,
            descriptionEn = "**EXPLOSION! Castle -5. (trap — triggers on draw)**",
            nameAccusative = "Bombu"),
        "C38" to CardPres("Okamžitě zahraj. Lízni kartu a -5 hradu.",
            R.drawable.art_explodovana_bomba, "Chaos",
            artScale = 0.80f, artBiasY = -0.6f,
            descriptionEn = "Play immediately. Draw a card and -5 castle."),
        "C39" to CardPres("Oba hráči zahodí celou ruku a líznou stejný počet nových karet.",
            R.drawable.art_velky_zmatek, "Chaos",
            artScale = 0.80f, artBiasY = 0.20f,
            descriptionEn = "Both players discard their entire hand and draw the same number of new cards."),

        // ── Lízni karet ───────────────────────────────────────────────────────
        "D01" to CardPres("Lízni 1 kartu.\n[Combo]",
            R.drawable.art_pruzkumnik, "Magie",
            artScale = 0.80f, artBiasY = 0.30f, isBasic = true),
        "D02" to CardPres("Lízni 2 karty.",
            R.drawable.art_vestba, "Magie",
            artScale = 0.80f, artBiasY = -1.00f),
        "D03" to CardPres("Lízni 3 karty.",
            R.drawable.art_kronika, "Magie",
            artScale = 0.80f, artBiasY = 0.20f),
        "D04" to CardPres("Zaútočí za 4. Lízni 1 kartu.",
            R.drawable.art_bojova_taktika, "Útok",
            artScale = 0.80f, isBasic = true),
        "D05" to CardPres("Hradby +4. Lízni 1 kartu.\n[Combo]",
            R.drawable.art_stavebni_plany, "Stavba",
            artScale = 0.80f),
        "D06" to CardPres("Zaútočí za 8. Lízni 1 kartu.",
            R.drawable.art_elitni_zved, "Útok",
            artScale = 0.80f, artBiasY = -0.35f),
        "D07" to CardPres("Lízni 2 karty. Důl magie +1.",
            R.drawable.art_tajna_knihovna, "Důl",
            artScale = 0.80f, artBiasY = 0.15f),
        "D08" to CardPres("Pokud máš >4 magie, lízni 2 karty.",
            R.drawable.art_vize, "Magie",
            artScale = 0.80f, artBiasY = -0.40f),
        "D09" to CardPres("**Toto kolo:** za každou další zahranou **MAGII** lízni 1. [Combo]",
            R.drawable.art_inspirace, "Magie",
            artScale = 0.90f, artBiasY = -1.0f),

        "113" to CardPres("**Rozhodnutí:** Vyber si 1 magickou kartu ze hry. Zlevni ji o 2. [Combo]",
            R.drawable.art_goblin_saman, "Magie",
            artScale = 0.80f, artBiasY = -1.00f),
        "114" to CardPres("**Rozhodnutí:** Vyber si 1 chaotickou kartu ze hry. Zlevni ji o 2. [Combo]",
            R.drawable.art_chaoticky_mudrc, "Chaos",
            artScale = 0.80f, artBiasY = -1.00f),
        "115" to CardPres("Oba hráči líznou 2 karty.\n[Combo]",
            R.drawable.art_studna_vedomosti, "Magie",
            artScale = 0.80f, artBiasY = -1.00f),
        "116" to CardPres("**Toto kolo:** příští karta, co zahraješ, se 2× zkopíruje do balíčku. [Combo]",
            R.drawable.art_chaoticka_replikace, "Chaos",
            artScale = 0.90f, artBiasY = -0.30f),
        "117" to CardPres("**Rozhodnutí:** vyber si 1 ze 4 různých dolů. [Combo]",
            R.drawable.art_pruzkum_dolu, "Magie",
            artScale = 0.85f, artBiasY = 0.25f),
        "118" to CardPres(
            "**Rozhodnutí:** vyber si kartu, která se hodí do situace. [Combo]",
            R.drawable.art_magicky_zolik, "Magie",
            artScale = 0.8f, artBiasX = 0.15f, artBiasY = -0.20f,
            descriptionEn = "**Decision:** choose a card that fits the situation — 1 best from each type (Magic, Attack, Build, Chaos). [Combo]",
            nameAccusative = "Magického žolíka"
        ),
        "120" to CardPres(
            "Všechny karty v tvé ruce zlevní o 1.",
            R.drawable.art_hromadna_sleva, "Magie",
            artScale = 0.80f, artBiasY = 0.45f,
            descriptionEn = "All cards in your hand cost 1 less."
        ),
        "121" to CardPres(
            "Všechny karty v soupeřově ruce zdraží o 1.",
            R.drawable.art_kletba_cen, "Chaos",
            artScale = 0.80f, artBiasY = 0.70f,
            descriptionEn = "All cards in the opponent's hand cost 1 more."
        ),
        "123" to CardPres(
            "Zaútočí za 2 + 4 za každou útočnou kartu zahranou v tomto tahu.",
            R.drawable.art_momentum, "Útok",
            artScale = 0.80f, artBiasY = 1.0f,
            descriptionEn = "Attack for 2 + 4 per Attack card played this turn.",
            nameAccusative = "Momentum"
        ),
        "124" to CardPres(
            "**Rozhodnutí:** získej 4 magie, 4 útok, nebo 4 kameny. [Combo]",
            R.drawable.art_alchymistova_volba, "Magie",
            artScale = 0.80f, artBiasY = -0.30f,
            descriptionEn = "**Decision:** gain 4 Magic, 4 Attack, or 4 Stones. [Combo]",
            nameAccusative = "Alchymistovu volbu"
        ),
        "125" to CardPres(
            "Zaútočí za 4. **Toto kolo:** každá zahraná **ÚTOK** karta přidá 2 chaos. [Combo]",
            R.drawable.art_valecny_zapal, "Útok",
            artScale = 0.80f, artBiasY = 0.15f,
            descriptionEn = "Attack for 4. **This turn:** each **ATTACK**\ncard played adds 2 Chaos. [Combo]",
            nameAccusative = "Válečný zápal"
        ),
        "126" to CardPres(
            "Chaos +2. **Toto kolo:** každá magická karta přidá 2 chaos. [Combo]",
            R.drawable.art_magicky_proud, "Magie",
            artScale = 0.80f, artBiasY = -0.60f,
            descriptionEn = "Chaos +2. **This turn:** each Magic card adds 2 chaos. [Combo]",
            nameAccusative = "Magický proud"
        ),
        "127" to CardPres(
            "Udeř hrad -10, znič 2 magie soupeři.",
            R.drawable.art_pyroblast, "Magie",
            artScale = 0.80f, artBiasY = -0.30f,
            descriptionEn = "Direct castle hit for 10, destroy 2 of the opponent's Magic.",
            nameAccusative = "Pyroblast"
        ),
        "128" to CardPres(
            "**Toto kolo:** za každou další zahranou kartu lízni 1 a získej 1 magii. [Combo]",
            R.drawable.art_archmag, "Magie",
            artScale = 0.80f, artBiasY = 0.40f,
            descriptionEn = "**This turn:** for each additional card played, draw 1 and gain 1 Magic. [Combo]",
            nameAccusative = "Archmága"
        ),
        "C43" to CardPres(
            "Zaútočí za 2. Příští karta, kterou zahraješ, se chová jako [Combo]. [Combo]",
            R.drawable.art_najezd, "Útok",
            artScale = 0.80f, artBiasY = -0.5f,
            descriptionEn = "Deal 2 damage. The next card you play acts as [Combo]. [Combo]",
            nameAccusative = "Nájezd"
        ),
        "C42" to CardPres(
            "Zkopíruje efekt poslední karty, co jsi zahrál. Cena = originál +1. [Combo]",
            R.drawable.art_klon, "Chaos",
            artScale = 0.75f, artBiasY = -0.75f,
            descriptionEn = "Copies the effect of the last card you played. Cost = original +1. [Combo]",
            nameAccusative = "Klon"
        ),
        "C41" to CardPres(
            "Zkopíruje efekt poslední soupeřovy karty. [Combo]",
            R.drawable.art_zrcadlo, "Chaos",
            artScale = 0.75f, artBiasY = -0.20f,
            descriptionEn = "Copies the effect of the opponent's last played card. [Combo]",
            nameAccusative = "Zrcadlo"
        ),
        "C40" to CardPres(
            "Vidíš celou soupeřovu ruku. Vyber jednu kartu a ukradni ji.",
            R.drawable.art_zakerny_speh, "Chaos",
            artScale = 0.80f, artBiasY = -0.5f,
            descriptionEn = "See the opponent's entire hand. Choose one card and steal it.",
            nameAccusative = "Zákeřného špeha"
        ),
        "119" to CardPres(
            "Zaútočí za 7. Dostaneš náhodnou útočnou kartu do ruky. [Combo]",
            R.drawable.art_valecny_pokrik, "Útok",
            artScale = 0.80f, artBiasY = -0.40f,
            descriptionEn = "Attack for 7. Get a random Attack card into your hand. [Combo]",
            nameAccusative = "Válečný pokřik"
        ),
        "122" to CardPres(
            "Postaví hrad o 7. Dostaneš náhodnou stavební kartu do ruky. [Combo]",
            R.drawable.art_stavebni_posila, "Stavba",
            artScale = 0.80f, artBiasY = -0.20f,
            descriptionEn = "Build castle for 7. Get a random Build card into your hand. [Combo]",
            nameAccusative = "Stavební posilu"
        ),
        "L01" to CardPres(
            "Ukradne 3 magie, útoku a kamenů. Udeř hrad -18. Ukradne 5 HP hradu.",
            R.drawable.art_darkmage, "Chaos",
            artScale = 0.80f, artBiasX = 0.10f, artBiasY = -1.0f,
            descriptionEn = "Steals 3 magic, attack, and stone. Deals 18 direct castle damage (ignores walls). Steals 5 castle HP.",
            nameAccusative = "Temného mága"
        ),
    )
}
