package com.example.termiti

/**
 * Prezentační data karty – vše, co je specifické pro Android klienta.
 * Herní data (cost, effects, rarity…) jsou v cards.js / cards.json.
 *
 * Při přidání nové karty do cards.js stačí volitelně přidat záznam sem
 * pro art, zvuk a popis. Karta bez záznamu funguje, ale zobrazí se
 * bez ilustrace a s prázdným popisem.
 */
data class CardPres(
    val description: String   = "",
    val artResId:    Int?     = null,
    val type:        String   = "",
    val artBiasX:    Float    = 0f,
    val artBiasY:    Float    = 0f,
    val artScale:    Float    = 1f,
    val isBasic:     Boolean  = false,
    val sound:       CardSound? = null,
    val soundResId:  Int?     = null
)

object CardPresentation {
    val presentations: Map<String, CardPres> = mapOf(

        // ── Útok (platí ATTACK) ───────────────────────────────────────────────
        "001" to CardPres("Zaútočí na nepřítele za 5. [Combo]",
            R.drawable.art_zakladni_utok, "Útok", isBasic = true),
        "008" to CardPres("Zaútočí na hrad za 3.",
            R.drawable.art_sipy, "Útok",
            soundResId = R.raw.arrow_hit),
        "003" to CardPres("Přímý zásah ohněm: hrad −8.",
            R.drawable.art_ohniva_koule, "Útok", artBiasY = -0.60f,
            soundResId = R.raw.fireball),
        "007" to CardPres("Zaútočí na nepřítele za 11.",
            R.drawable.art_silny_uder, "Útok",
            artScale = 0.80f, artBiasY = -1.00f, isBasic = true),
        "006" to CardPres("Pokud máš více útoku než soupeř, udeř hrad za 10.",
            R.drawable.art_prevaha_sily,
            artScale = 0.80f, artBiasY = -0.10f),
        "017" to CardPres("Zaútočí za 8, ukradni 2 útoku soupeři.",
            R.drawable.art_valecny_sekyrnik, "Útok",
            artScale = 0.80f, artBiasY = -1.00f),

        // ── Stavba (platí STONES) ─────────────────────────────────────────────
        "002" to CardPres("Postaví hradby +9.",
            R.drawable.art_kamenna_zed, "Stavba",
            artBiasX = -0.50f, artBiasY = -1.00f, artScale = 0.80f, isBasic = true),
        "010" to CardPres("Hradby +5, vrátí 1 kámen.",
            R.drawable.art_palisada, "Stavba",
            artScale = 0.80f, artBiasY = -1.00f, isBasic = true),
        "005" to CardPres("Opraví hrad o 4.",
            R.drawable.art_posila_hradu, "Stavba",
            artScale = 0.80f, artBiasY = -0.30f, isBasic = true),
        "009" to CardPres("Opraví hrad o 8.",
            R.drawable.art_pevne_zaklady, "Stavba",
            artScale = 0.80f, artBiasY = 0.50f, isBasic = true),
        "018" to CardPres("Postaví hradby +15.",
            R.drawable.art_mohutna_vez, "Stavba",
            artScale = 0.90f, artBiasY = -1.00f),

        // ── Zdroje okamžité (platí MAGIC) ────────────────────────────────────
        "004" to CardPres("Okamžitě +2 magie. [Combo]",
            R.drawable.art_magie, "Magie", artBiasY = -1.00f, isBasic = true),
        "011" to CardPres("Okamžitě +4 kameny. [Combo]",
            R.drawable.art_zasoby_kamene, "Magie",
            artScale = 0.80f, artBiasY = -0.55f, isBasic = true),
        "012" to CardPres("Okamžitě +3 útoku. [Combo]",
            R.drawable.art_mobilizace, "Magie",
            artScale = 0.80f, artBiasY = -0.30f, isBasic = true),

        // ── Doly (platí MAGIC) ────────────────────────────────────────────────
        "013" to CardPres("Trvale +1 důl magie/kolo.",
            R.drawable.art_magicky_pramen, "Důl",
            artScale = 0.80f, artBiasY = -0.40f, isBasic = true),
        "014" to CardPres("Trvale +1 důl kamene/kolo.",
            R.drawable.art_kamenolom, "Důl",
            artScale = 0.75f, artBiasY = -0.30f, isBasic = true),
        "015" to CardPres("Trvale +1 důl útoku/kolo.",
            R.drawable.art_vycvikovy_tabor, "Důl",
            artScale = 0.85f, artBiasY = -0.20f, isBasic = true),
        "016" to CardPres("Trvale +2 doly magie/kolo.",
            R.drawable.art_velky_pramen, "Důl",
            artScale = 0.75f, artBiasY = -0.55f),

        // ── Útok – rozšíření ──────────────────────────────────────────────────
        "019" to CardPres("Poškodí jen hradby o 5.",
            R.drawable.art_zapalne_sipy, "Útok",
            artScale = 0.80f, artBiasY = -1.00f, soundResId = R.raw.arrow_hit),
        "020" to CardPres("[Combo] Poškodí jen hradby o 12.",
            R.drawable.art_beranidlo, "Útok",
            artScale = 0.85f, artBiasY = 0.05f),
        "021" to CardPres("Zaútočí na nepřítele za 15.",
            R.drawable.art_delostrelectvo, "Útok",
            artScale = 0.80f, artBiasY = 0.05f, soundResId = R.raw.delostrelectvo),
        "022" to CardPres("Poškodí hrad −8.",
            R.drawable.art_primy_zasah, "Útok",
            artScale = 0.80f, artBiasY = -1.00f),
        "023" to CardPres("Zaútočí na hrad za 7 a hradby za 7.",
            R.drawable.art_dvojity_utok, "Útok",
            artScale = 0.80f, artBiasY = -1.00f),
        "024" to CardPres("Pokud máš <5 hradeb, udeř hrad za 13.",
            R.drawable.art_berserk, "Útok",
            artScale = 0.75f, artBiasY = -0.50f),
        "025" to CardPres("Pokud máš <10 hradeb, udeř hrad za 10.",
            R.drawable.art_protiutok, "Útok",
            artScale = 0.80f, artBiasY = -0.50f),
        "026" to CardPres("Poškodí hrad o 5. Pokud >5 útoku, +5.",
            R.drawable.art_ostrelovac, "Útok",
            artScale = 0.85f, artBiasY = 0.10f),
        "027" to CardPres("Zaútočí za 4. **Toto kolo:** za každou zahranou **ÚTOK** +2 útoku. [Combo]",
            R.drawable.art_valecne_bubny, "Útok",
            artScale = 0.80f, artBiasY = -0.60f, soundResId = R.raw.drums_of_war),

        // ── Stavba – rozšíření ────────────────────────────────────────────────
        "028" to CardPres("Opraví hrad o 3.",
            R.drawable.art_zaplata, "Stavba",
            artBiasX = 0.50f, artBiasY = -1.00f, artScale = 0.85f),
        "029" to CardPres("Postaví hradby +6. [Combo]",
            R.drawable.art_opevneni, "Stavba",
            artScale = 0.80f, artBiasY = 0.55f),
        "030" to CardPres("Postaví hradby +13.",
            R.drawable.art_kamenny_val, "Stavba",
            artScale = 0.80f, artBiasY = -1.00f),
        "031" to CardPres("Opraví hrad o 6.",
            R.drawable.art_renovace, "Stavba",
            artScale = 0.85f, artBiasY = -1.00f, isBasic = true),
        "032" to CardPres("Opraví hrad o 13.",
            R.drawable.art_citadela, "Stavba",
            artScale = 0.80f, artBiasY = -0.80f),
        "033" to CardPres("Pokud máš <8 hradeb, postav +11.",
            R.drawable.art_zemni_val, "Stavba",
            artScale = 0.80f, artBiasY = -1.00f),
        "034" to CardPres("Pokud máš >15 hradeb, oprav hrad o 8.",
            R.drawable.art_opravar, "Stavba",
            artScale = 0.80f, artBiasY = 0.25f),
        "035" to CardPres("Hradby +5 a hrad +4.",
            R.drawable.art_zakladni_kamen, "Stavba",
            artScale = 0.80f, artBiasY = 0.25f),
        "036" to CardPres("Hradby +7. Pokud hrad <35, hradby +5.",
            R.drawable.art_hradni_prikop, "Stavba",
            artScale = 0.80f, artBiasY = -0.95f),

        // ── Zdroje – rozšíření ────────────────────────────────────────────────
        "037" to CardPres("Okamžitě +4 magie. [Combo]",
            R.drawable.art_rychla_magie, "Magie",
            artScale = 0.75f, artBiasY = -0.35f),
        "038" to CardPres("Okamžitě +6 útoku. [Combo]",
            R.drawable.art_vojensky_rozkaz, "Magie",
            artScale = 0.80f, isBasic = true),
        "039" to CardPres("Okamžitě +6 kamene. [Combo]",
            R.drawable.art_stavebni_boom, "Stavba",
            artScale = 0.80f, artBiasY = 0.25f, isBasic = true),
        "040" to CardPres("Pokud máš >4 magie, získej +8 útoku.",
            R.drawable.art_alchymie, "Magie"),
        "041" to CardPres("+2 magie, +2 útoku, +2 kamene. [Combo]",
            R.drawable.art_magicke_trio, "Magie",
            artScale = 0.80f, artBiasY = -1.00f),

        // ── Doly – rozšíření ──────────────────────────────────────────────────
        "042" to CardPres("Trvale +2 doly kamene/kolo.",
            R.drawable.art_velky_kamenolom, "Magie",
            artScale = 0.80f, artBiasY = 0.25f),
        "043" to CardPres("Trvale +2 doly útoku/kolo.",
            R.drawable.art_vycvikove_centrum, "Magie",
            artScale = 0.85f),
        "044" to CardPres("+1 důl magie, útoku i kamene/kolo.",
            R.drawable.art_trifekta_dolu, "Důl",
            artScale = 0.80f, artBiasY = -0.35f),
        "045" to CardPres("Trvale +3 doly magie/kolo.",
            R.drawable.art_ocarovane_doly, "Důl",
            artScale = 0.80f),

        // ── Útok – Arcomage/Mravenci inspirace ────────────────────────────────
        "046" to CardPres("Zaútočí za 2, ukradni 1 magii, +1 chaosu.",
            R.drawable.art_goblin, "Útok", artScale = 0.80f),
        "047" to CardPres("Zaútočí na nepřítele za 9.",
            R.drawable.art_ogr, "Útok",
            artScale = 0.80f, isBasic = true, soundResId = R.raw.ogr),
        "048" to CardPres("Zaútočí za 6, získej +3 magie. [Combo]",
            R.drawable.art_upir, "Útok",
            artScale = 0.80f, artBiasY = -1.00f),
        "049" to CardPres("Zaútočí za 3, soupeř ztratí 3 magie, +1 chaosu.",
            R.drawable.art_jed, "Útok",
            artScale = 0.80f, artBiasY = -0.50f, soundResId = R.raw.jed),
        "050" to CardPres("Zaútočí za 8, soupeř ztratí 4 kameny.",
            R.drawable.art_podkopani_hradeb, "Útok",
            artScale = 0.80f, artBiasY = 0.35f),
        "051" to CardPres("Zaútočí za 14, hrad −8 přímo, +2 chaosu.",
            R.drawable.art_drak, "Útok",
            artScale = 0.80f, artBiasY = -1.00f, soundResId = R.raw.dragon_breath),
        "052" to CardPres("Přímý zásah: hrad −16. +2 chaosu.",
            R.drawable.art_demon, "Útok",
            artScale = 0.80f, artBiasY = -0.50f, soundResId = R.raw.demon_laugh),
        "053" to CardPres("Poškodí jen hradby o 10, získej +2 útoku.",
            R.drawable.art_plamenomet, "Útok",
            artBiasX = -1.00f, artBiasY = -0.05f, artScale = 0.80f),
        "054" to CardPres("Zaútočí na nepřítele za 13, +2 útoku.",
            R.drawable.art_valecny_pochod, "Útok",
            artScale = 0.80f, artBiasY = -0.30f),
        "055" to CardPres("Zaútočí za 3, +1 útoku. Pokud <5 hradeb: hrad −8.",
            R.drawable.art_posledni_vzdor, "Útok",
            artScale = 0.80f, artBiasY = -1.00f),
        "056" to CardPres("Ukradni 3 útoku, zaútočí za 4.",
            R.drawable.art_najezdnik, "Útok",
            artScale = 0.80f, artBiasY = -0.65f, isBasic = true),

        // ── Stavba – Arcomage/Mravenci inspirace ──────────────────────────────
        "057" to CardPres("Hradby +7, +1 kámen.",
            R.drawable.art_basta, "Stavba",
            artScale = 0.80f, artBiasY = -1.00f),
        "058" to CardPres("Hradby +4. [Combo]",
            R.drawable.art_obranny_val, "Stavba",
            artScale = 0.80f),
        "059" to CardPres("Hradby +5 a hrad +7.",
            R.drawable.art_pevnostni_hrad, "Stavba",
            artScale = 0.80f, artBiasY = -0.50f, isBasic = true),
        "060" to CardPres("Hrad +18.",
            R.drawable.art_chram, "Stavba",
            artScale = 0.80f, artBiasY = -0.25f),
        "061" to CardPres("Pokud hrad <40, postav hradby +12.",
            R.drawable.art_tunely, "Stavba",
            artScale = 0.80f),
        "062" to CardPres("Hradby +7, hrad +4, +2 kameny.",
            R.drawable.art_obranna_aliance, "Stavba",
            artScale = 0.80f, artBiasY = -0.05f),
        "063" to CardPres("Hradby +11, trvale +1 důl kamene.",
            R.drawable.art_vez_strazni, "Stavba",
            artScale = 0.80f, artBiasY = -1.00f),
        "064" to CardPres("Pokud hrad <40, oprav hrad o 10.",
            R.drawable.art_zasobnik, "Stavba",
            artScale = 0.80f, artBiasY = -0.50f),

        // ── Sabotáž a krádež (platí MAGIC) ────────────────────────────────────
        "065" to CardPres("Ukradni 4 útoku od soupeře.",
            R.drawable.art_lupic, "Magie",
            artScale = 0.90f, artBiasY = -0.25f, isBasic = true),
        "066" to CardPres("Ukradni 4 kameny od soupeře.",
            R.drawable.art_kamenna_dan, "Magie",
            artScale = 0.80f),
        "067" to CardPres("Soupeř ztratí 5 kamenů.",
            R.drawable.art_saboter, "Magie",
            artBiasX = -1.00f, artBiasY = 0.40f, artScale = 0.80f),
        "068" to CardPres("Soupeř ztratí 5 útoku.",
            R.drawable.art_demoralizace, "Magie",
            artScale = 0.80f, artBiasY = 0.30f),
        "069" to CardPres("Ukradni 3 magie a 3 útoku, +1 chaosu.",
            R.drawable.art_dvojity_agent, "Magie",
            artScale = 0.80f, artBiasY = -0.60f),
        "070" to CardPres("Soupeř ztratí 5 kamenů a 5 útoku.",
            R.drawable.art_krize_zasobovani, "Magie",
            artScale = 0.80f, artBiasY = -0.05f),
        "071" to CardPres("Ukradni 2 od každého zdroje, +2 chaosu.",
            R.drawable.art_spion, "Magie",
            artScale = 0.80f, artBiasY = -1.00f),

        // ── Zdroje + doly – Arcomage/Mravenci inspirace ───────────────────────
        "072" to CardPres("+2 útoku, trvale +1 důl útoku.",
            R.drawable.art_zbrojnice, "Magie",
            artScale = 0.80f, artBiasY = 0.60f),
        "073" to CardPres("+2 magie, trvale +1 důl magie.",
            R.drawable.art_skola_magie, "Magie",
            artScale = 0.80f, artBiasY = 0.30f),
        "074" to CardPres("+3 magie, +3 útoku, +3 kameny. [Combo]",
            R.drawable.art_trziste, "Magie",
            artScale = 0.80f, artBiasY = 0.30f),
        "075" to CardPres("Trvale +2 magie a +1 kameny/kolo.",
            R.drawable.art_rozmach_tezby, "Důl",
            artScale = 0.80f, artBiasY = -1.00f),
        "076" to CardPres("Trvale +2 útoku a +1 kameny/kolo.",
            R.drawable.art_vojenska_zakladna, "Důl",
            artScale = 0.80f, artBiasY = -1.00f),
        "077" to CardPres("Pokud máš >8 magie, získej +10 útoku.",
            R.drawable.art_premena_magie, "Magie",
            artScale = 0.80f, artBiasY = -1.00f),
        "078" to CardPres("Přímý zásah: hrad −10, ukradni 4 magie a 4 útoku, +2 chaosu.",
            R.drawable.art_draci_upir, "Útok",
            artScale = 0.80f, artBiasY = -1.00f, soundResId = R.raw.dragon_breath),
        "079" to CardPres("Zaútočí za 12, soupeř ztratí 3 magie, +2 chaosu.",
            R.drawable.art_oblehani, "Útok",
            artScale = 0.75f, artBiasY = -0.45f),
        "080" to CardPres("+2 každý důl.",
            R.drawable.art_velkovyroba, "Důl",
            artScale = 0.80f),

        // ── Stavba – nové posily (STONES buff) ───────────────────────────────
        "081" to CardPres("Postaví hradby +7.",
            R.drawable.art_rychla_hradba, "Stavba",
            artScale = 0.80f, artBiasY = -0.65f),
        "082" to CardPres("Postaví hradby +18.",
            R.drawable.art_masivni_zed, "Stavba",
            artScale = 0.80f, artBiasY = -0.45f),
        "083" to CardPres("Pokud máš <10 hradeb, postav +14.",
            R.drawable.art_nouzove_opevneni, "Stavba",
            artScale = 0.80f, artBiasY = -0.60f),
        "084" to CardPres("Hradby +4 a hrad +7.",
            R.drawable.art_velka_oprava, "Stavba",
            artScale = 0.80f, artBiasY = -0.20f),
        "085" to CardPres("Oprav hrad o 15.",
            R.drawable.art_kralovska_obnova, "Stavba",
            artScale = 0.80f, artBiasY = 0.50f),
        "086" to CardPres("Hradby +8 a hrad +6.",
            R.drawable.art_zednicka_rota, "Stavba",
            artScale = 0.80f),
        "087" to CardPres("Hradby +10 a hrad +8.",
            R.drawable.art_pevnost, "Stavba",
            artScale = 0.80f, artBiasY = -1.00f),
        "088" to CardPres("Hradby +10. Pokud máš >30 hradu, +6 navíc.",
            R.drawable.art_zesilene_hradby, "Stavba",
            artScale = 0.80f, artBiasY = -1.00f),
        "089" to CardPres("Hradby +5, trvale +1 důl kamene/kolo.",
            R.drawable.art_architekt, "Důl",
            artScale = 0.80f, artBiasY = -0.60f),
        "090" to CardPres("Trvale +2 doly kamene/kolo.",
            R.drawable.art_rozsireni_tezby, "Důl",
            artScale = 0.80f, artBiasY = -0.25f),
        "091" to CardPres("Hradby +9. Soupeř ztratí 2 útoku.",
            R.drawable.art_barikady, "Stavba",
            artScale = 0.80f, artBiasY = -0.95f),
        "092" to CardPres("Pokud máš >20 hradeb, postav +14.",
            R.drawable.art_strategicka_vystavba, "Stavba",
            artScale = 0.80f, artBiasY = -0.55f),
        "093" to CardPres("+5 hrad. **Toto kolo:** za každou zahranou **STAVBU** +3 hrad. [Combo]",
            R.drawable.art_cihla_na_cihlu, "Stavba",
            artScale = 0.80f),
        "094" to CardPres("Hradby +6, získej +2 kameny. [Combo]",
            R.drawable.art_sklad_materialu, "Stavba",
            artScale = 0.80f),
        "095" to CardPres("Získej +5 kamenů.",
            R.drawable.art_obchod_s_kamenem, "Stavba",
            artScale = 0.80f),
        "096" to CardPres("Hradby +18, Hrad +8.",
            R.drawable.art_nedobytna_pevnost, "Stavba",
            artScale = 0.80f),
        "097" to CardPres("Hrad +25.",
            R.drawable.art_obnova_kralovstvi, "Stavba",
            artScale = 0.80f),
        "098" to CardPres("Vlastní hradby −4, zaútočí na nepřítele za 11.",
            R.drawable.art_hod_cihlou, "Útok",
            artScale = 0.80f, artBiasY = 0.15f),
        "099" to CardPres("Ukradni 10 životů hradu soupeři.",
            R.drawable.art_temny_prenos, "Magie",
            artScale = 0.80f, artBiasY = -1.00f),
        "100" to CardPres("Zaútočí za 5, ukradni 6 životů hradu.",
            R.drawable.art_krvavy_uder, "Útok",
            artBiasX = -1.00f, artScale = 0.80f),

        // ── X-kost karty ──────────────────────────────────────────────────────
        "101" to CardPres("Spotřebuje veškerý útok. Přímý zásah hradu za X/2.",
            R.drawable.art_nahla_smrt, "Útok",
            artBiasX = 0.25f, artBiasY = -0.30f, artScale = 0.80f),
        "102" to CardPres("Spotřebuje veškerý kámen. Opraví hrad o X/2.",
            R.drawable.art_kamenny_prival, "Stavba",
            artScale = 0.80f, artBiasY = -1.00f),
        "103" to CardPres("Spotřebuje veškerou magii. Přidá X/2 útoku a X/2 kamene.",
            R.drawable.art_magicke_rozdeleni, "Magie",
            artScale = 0.80f, artBiasY = -0.40f),

        // ── Chaos – generátory chaosu (platí MAGIC) ───────────────────────────
        "C01" to CardPres("+2 chaosu. [Combo]",
            R.drawable.art_chaoticka_jiskra, "Magie",
            artScale = 0.80f, artBiasY = -1.00f),
        "C02" to CardPres("+5 chaosu. Soupeř ztratí 2 magie.",
            R.drawable.art_entropie, "Magie",
            artScale = 0.80f),
        "C03" to CardPres("Trvale +1 důl chaosu/kolo.",
            R.drawable.art_chaoticky_dul, "Magie",
            artScale = 0.80f),
        "C04" to CardPres("Ukradni 3 chaos od soupeře. [Combo]",
            R.drawable.art_kradez_chaosu, "Magie",
            artScale = 0.80f, artBiasY = -0.55f),

        // ── Chaos – karty platící chaosem ────────────────────────────────────
        "C05" to CardPres("Přímý zásah: hrad −14, ignoruje hradby.",
            R.drawable.art_chaoticky_vybuch, "Magie",
            artScale = 0.80f, artBiasY = 0.30f),
        "C06" to CardPres("Zaútočí na nepřítele za 20.",
            R.drawable.art_boure_chaosu, "Magie",
            artScale = 0.75f, artBiasY = -0.60f),
        "C07" to CardPres("Hradby +16.",
            R.drawable.art_chaoticky_stit, "Stavba",
            artScale = 0.80f, artBiasY = -0.20f),
        "C08" to CardPres("Hrad +15.",
            R.drawable.art_zazrak_chaosu, "Stavba",
            artScale = 0.80f, artBiasY = -0.20f),
        "C09" to CardPres("Soupeř ztratí 6 od každého zdroje.",
            R.drawable.art_chaoticka_krize, "Chaos",
            artScale = 0.80f),
        "C10" to CardPres("Zaútočí za 15, hrad −12 přímo.",
            R.drawable.art_chaoticky_drak, "Útok",
            artScale = 0.80f, artBiasY = -1.00f, soundResId = R.raw.dragon_breath),
        "C11" to CardPres("Hrad +8 a hradby +8.",
            R.drawable.art_chaos_a_rad, "Stavba",
            artScale = 0.80f, artBiasY = -0.35f),
        "C12" to CardPres("Ukradni 5 od každého zdroje soupeře.",
            R.drawable.art_anarchie, "Chaos",
            artScale = 0.80f, artBiasY = -0.90f),

        // ── Chaos – ničení dolů ───────────────────────────────────────────────
        "C13" to CardPres("Znič 1 důl magie (min. 1). Zablokuj produkci na 2 kola.",
            R.drawable.art_sabotaz, "Chaos",
            artScale = 0.80f, artBiasY = -0.20f),
        "C14" to CardPres("Znič 1 důl kamene (min. 1). Zablokuj produkci na 2 kola.",
            R.drawable.art_niceni_kamenolomu, "Chaos",
            artScale = 0.80f, artBiasY = -0.85f),
        "C15" to CardPres("Znič 1 útočný výcvik (min. 1). Zablokuj produkci na 2 kola.",
            R.drawable.art_zakernost, "Chaos",
            artScale = 0.80f, artBiasY = 0.35f),
        "C16" to CardPres("Znič důl magie a kamene (min. 1). Zablokuj produkci na 3 kola.",
            R.drawable.art_velka_sabotaz, "Útok",
            artScale = 0.80f, artBiasY = -1.00f),

        // ── Chaos – krádež a ničení karet ─────────────────────────────────────
        "C17" to CardPres("Ukradni 1 náhodnou kartu ze soupeřovy ruky.",
            R.drawable.art_telekineze, "Chaos",
            artScale = 0.80f, artBiasY = -1.00f),
        "C18" to CardPres("Ukradni 2 náhodné karty ze soupeřovy ruky.",
            R.drawable.art_kradez_osudu, "Chaos",
            artScale = 0.80f, artBiasY = -0.75f),
        "C19" to CardPres("Znič 2 náhodné karty ze soupeřovy ruky.",
            R.drawable.art_spalena_knihovna, "Magie",
            artScale = 0.80f, artBiasY = 0.10f),
        "C20" to CardPres("Znič 3 náhodné karty ze soupeřovy ruky.",
            R.drawable.art_prazdna_mysl, "Chaos",
            artScale = 0.80f, artBiasY = -0.45f),

        // ── Chaos – přidání karet do balíčku ──────────────────────────────────
        "C21" to CardPres("Přidej 3 kopie 'Šípy' do svého balíčku.",
            R.drawable.art_replikace, "Chaos",
            artScale = 0.80f, artBiasY = -0.35f),
        "C22" to CardPres("Přidej 2 'Chaos výbuch' do svého balíčku.",
            R.drawable.art_chaos_manufaktura, "Chaos",
            artScale = 0.80f),
        "C23" to CardPres("Přidej 2 kopie 'Rychlý útok' do svého balíčku.",
            R.drawable.art_klonovani, "Chaos",
            artScale = 0.75f, artBiasY = -0.20f),

        // ── Chaos – nové generátory ───────────────────────────────────────────
        "C24" to CardPres("+5 chaosu. [Combo]",
            R.drawable.art_temny_ritual, "Magie",
            artScale = 0.80f, artBiasY = 0.30f),
        "C25" to CardPres("+2 chaosu a +2 magie. [Combo]",
            R.drawable.art_nestabilni_vir, "Magie",
            artScale = 0.80f, artBiasY = -0.75f),
        "C26" to CardPres("+4 chaosu. [Combo]",
            R.drawable.art_krvava_obet, "Magie",
            artScale = 0.80f),
        "C27" to CardPres("Pokud máš >5 magie, získej +7 chaosu.",
            R.drawable.art_odraz_magie, "Magie",
            artScale = 0.80f, artBiasY = -1.00f),
        "C28" to CardPres("Ukradni 2 útoku, +3 chaosu. [Combo]",
            R.drawable.art_chaoticka_trofej, "Chaos",
            artScale = 0.80f, artBiasY = -0.95f),
        "C29" to CardPres("+3 chaosu a trvale +1 důl chaosu.",
            R.drawable.art_bourliva_mysl, "Důl",
            artScale = 0.80f, artBiasY = -0.75f),
        "C30" to CardPres("Trvale +2 doly chaosu/kolo.",
            R.drawable.art_chram_chaosu, "Důl",
            artScale = 0.80f, artBiasY = -0.10f),
        "C31" to CardPres("+4 chaosu, soupeř ztratí 2 každého zdroje.",
            R.drawable.art_chaoticky_vymenik, "Chaos",
            artScale = 0.80f, artBiasY = 0.55f),
        "C32" to CardPres("Soupeř −10 hrad, vlastní hrad −10.",
            R.drawable.art_vzajemna_zkaza, "Chaos",
            artScale = 0.80f, artBiasY = -0.40f),
        "C33" to CardPres("Prohoď s oponentem celé ruce karet.",
            null, "Chaos"),
        "C34" to CardPres("Na začátku každého tahu se promění v náhodnou kartu ze hry.",
            R.drawable.art_shapeshifter, "Chaos",
            artScale = 0.80f),

        // ── Lízni karet ───────────────────────────────────────────────────────
        "D01" to CardPres("Lízni 1 kartu. [Combo]",
            R.drawable.art_pruzkumnik, "Magie",
            artScale = 0.80f, artBiasY = 0.30f, isBasic = true),
        "D02" to CardPres("Lízni 2 karty.",
            R.drawable.art_vestba, "Magie",
            artScale = 0.80f, artBiasY = -1.00f),
        "D03" to CardPres("Lízni 3 karty.",
            R.drawable.art_kronika, "Magie",
            artScale = 0.80f, artBiasY = 0.20f),
        "D04" to CardPres("Zaútočí za 4. Lízni 1 kartu.",
            R.drawable.art_bojova_taktika, "Útok",
            artScale = 0.80f, isBasic = true),
        "D05" to CardPres("Hradby +4. Lízni 1 kartu. [Combo]",
            R.drawable.art_stavebni_plany, "Stavba",
            artScale = 0.80f),
        "D06" to CardPres("Zaútočí za 8. Lízni 1 kartu.",
            R.drawable.art_elitni_zved, "Útok",
            artScale = 0.80f, artBiasY = -0.35f),
        "D07" to CardPres("Lízni 2 karty. Trvale +1 důl magie.",
            R.drawable.art_tajna_knihovna, "Magie",
            artScale = 0.80f, artBiasY = 0.15f),
        "D08" to CardPres("Pokud máš >4 magie, líz 2 karty.",
            R.drawable.art_vize, "Magie",
            artScale = 0.80f, artBiasY = -0.40f),
        "D09" to CardPres("**Toto kolo:** za každou další zahranou **MAGII** lízni 1. [Combo]",
            R.drawable.art_inspirace, "Magie",
            artScale = 0.80f),

        // ── Testovací ─────────────────────────────────────────────────────────
        "T01" to CardPres("+5 Magie.",
            R.drawable.art_goblin_saman, "Magie",
            artScale = 0.80f, artBiasY = -1.00f),
    )
}
